katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'
urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user 
from todolist.views import logout_user 
from todolist.views import new_list,add_task
from todolist.views import finish_task,delete_task,json


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('json/', json, name='json'),
    path('add/', add_task, name='add_task'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', new_list, name='new_list'),
    path('finish-task/<int:pk>/', finish_task, name='finish'),
    path('delete-task/<int:pk>/', delete_task, name='delete'),
]

todolist/models.py
from ast import mod
import imp
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class toDoList(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    finished = models.BooleanField(default=False)
    

todolist/forms.py
from cProfile import label
from todolist.models import toDoList
from django.forms import ModelForm

class todoForm(ModelForm):
    class Meta:
        model = toDoList
        fields = ['title','description','finished',]

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from todolist.forms import todoForm
import datetime
from django.http import HttpResponseRedirect
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.urls import reverse
from django.core import serializers
from todolist.models import toDoList
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data = toDoList.objects.filter(user=request.user)
    context = {
        'mytodolist': data,
        'nama': 'Balqis Lumbun/Oka',
        'npm': "2106751184",
        'uname':username_in(request),
        'last_login': request.COOKIES['last_login'],
        
    }
    return render(request, "todolist.html", context)

def username_in(request):
    username = None
    if request.user.is_authenticated:
        username = request.user.username
        return username

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
# @csrf_exempt
def new_list(request):
    if request.method == 'POST':
        user = request.user
        title = request.POST.get('title')
        description = request.POST.get('description')
        finished = False
        addtask = toDoList(date=datetime.date.today(),user=user,title=title,description=description,finished=finished)
        addtask.save()
        return redirect('todolist:show_todolist')
    return render(request, "newtodo.html")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def finish_task(request, pk):
    lists=toDoList.objects.get(id=pk)
    if lists.finished == True:
        lists.finished = False            
    else:
        lists.finished = True
    lists.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete_task(request, pk):
    lists=toDoList.objects.get(id=pk)
    lists.delete()
    return redirect('todolist:show_todolist')

def json(request):
    data = toDoList.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def add_task(request):
    if request.method == 'POST':
        user = request.user
        title = request.POST.get("title")
        description = request.POST.get("description")
        finished = False

        new_to_do_list = toDoList( date=datetime.date.today(), title=title, description=description, user=user, finished=finished)
        new_to_do_list.save()

        return JsonResponse(
            {"pk" : new_to_do_list.pk, 
            "fields": {
            "date" : new_to_do_list.date,
            "title" : new_to_do_list.title,
            "description" : new_to_do_list.description,
            "is_finished" : new_to_do_list.finished,
        }})

    return HttpResponseNotFound()

todolist/templates/login.html
{% extends 'base.html' %} {% block content %}{% block meta %} {% load static %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/tutorial.css' %}" media="biasa2" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <style>
        h1 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        h3 {
            font-family: "Century Gothic";
            font-weight: bolder;
        }
        
        #bigspace h3 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        #bigspace h4 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        #bigspace h5 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        #bigspace h3:hover {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
            font-size: 50px;
            transition: 300ms linear;
        }
        
        h5 {
            color: #0d138f;
            font-family: "Century Gothic";
            font-weight: bolder;
        }
        
        b {
            color: #C90668;
            font-family: "Century Gothic";
            font-weight: bolder;
        }
        /* @table (min-width: 700px) {
            background-color: white;
        } */
        
        th {
            color: green;
            font-family: "Century Gothic";
        }
        
        a {
            color: white;
        }
        
        a:hover {
            color: orange;
        }
        
        #nav h5:hover {
            background-color: orange;
            font-size: 26px;
            transition: 300ms linear;
        }
        
        #cont {
            background-color: black;
        }
        
        body {
            background-color: #3BE3D5;
        }
        
        li {
            display: block;
            font-width: bold;
            font-family: "Century Gothic";
        }
        
        li:hover {
            font-size: 20px;
            transition: 300ms linear;
            font-width: bolder;
            font-family: "Century Gothic";
        }
        
        button {
            background-color: #0a68c7;
            border: none;
            border-radius: 8px;
        }
        
        .card button {
            background-color: #3042c9;
            min-width: 100px;
            max-width: 200px;
        }
        
        button:hover {
            font-size: 20px;
            transition: 200ms linear;
        }
        
        .nav-item {
            color: beige;
        }
        
        .card {
            background-color: #f9fce6;
            display: flex;
            min-width: 150px;
            max-width: 800px;
        }
        
        @media (max-width:1500px) {
            /* .beeg{

            display:flex;
        } */
            .card {
                display: flex;
            }
        }
        
        @media (min-width:200px) {
            /* .beeg{
            display:flex;
        } */
            .card {
                display: flex;
            }
        }
        
        #blank {
            padding: 10px;
        }
        
        #bigspace {
            background-color: #0d138f;
            padding: 40px;
        }
        
        #box {
            background-color: #080d6e;
            padding: 10px;
        }
        
        #nav {
            background-color: #ffb9b0;
            padding: 10px;
        }
    </style>

    <title>
        Logging In..
    </title>
</head>
{% endblock meta %}


<body>
    <center>
        <div id="nav">
            <h5>Balqis A. Lumbun - 2106751184</h5>
            <h5><a style="color:brown" href="{% url 'todolist:register' %}">Bikin Akun</a></h5>
        </div>
        <div id="bigspace">
            <h1>Login Dulu Yuk!</h1>
        </div>
        <div class="login">
            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>
                            <h5>Username: </h5>
                        </td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                    <br>
                    <tr>
                        <td>
                            <h5>Password: </h5>
                        </td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><button style="float: right;background-color:#3042c9;"><input class="btn login_btn"  style="color: white;" type="submit" value="Login"></button></td>
                    </tr>
                </table>
            </form>

            {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <br>
            <h5>Kamu belum ada akun ya?</h5><br><button style="background-color:#3042c9;"><a style="color: beige;" href="{% url 'todolist:register' %}">Buat Akun</a></button>

        </div>
    </center>
</body>

{% endblock content %}

todolist/templates/newtodo.html
{% extends 'base.html' %} {% load static %}{% block content %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <style>
        h1 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        h3 {
            font-family: "Century Gothic";
            font-weight: bolder;
        }
        
        #bigspace h3 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        #bigspace h4 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        #bigspace h5 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        #bigspace h3:hover {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
            font-size: 50px;
            transition: 300ms linear;
        }
        
        h5 {
            color: #0d138f;
            font-family: "Century Gothic";
            font-weight: bolder;
        }
        
        b {
            color: #C90668;
            font-family: "Century Gothic";
            font-weight: bolder;
        }
        /* @table (min-width: 700px) {
            background-color: white;
        } */
        
        th {
            color: green;
            font-family: "Century Gothic";
        }
        
        a {
            color: white;
        }
        
        a:hover {
            color: orange;
        }
        
        #nav h5:hover {
            background-color: orange;
            font-size: 26px;
            transition: 300ms linear;
        }
        
        #cont {
            background-color: black;
        }
        
        body {
            background-color: #3BE3D5;
        }
        
        li {
            display: block;
            font-width: bold;
            font-family: "Century Gothic";
        }
        
        li:hover {
            font-size: 20px;
            transition: 300ms linear;
            font-width: bolder;
            font-family: "Century Gothic";
        }
        
        button {
            background-color: #0a68c7;
            border: none;
            border-radius: 8px;
        }
        
        .card button {
            background-color: #3042c9;
            min-width: 100px;
            max-width: 200px;
        }
        
        button:hover {
            font-size: 20px;
            transition: 200ms linear;
        }
        
        .nav-item {
            color: beige;
        }
        
        .card {
            background-color: #f9fce6;
            display: flex;
            min-width: 150px;
            max-width: 800px;
        }
        
        @media (max-width:1500px) {
            /* .beeg{

            display:flex;
        } */
            .card {
                display: flex;
            }
        }
        
        @media (min-width:200px) {
            /* .beeg{
            display:flex;
        } */
            .card {
                display: flex;
            }
        }
        
        #blank {
            padding: 10px;
        }
        
        #bigspace {
            background-color: #0d138f;
            padding: 40px;
        }
        
        #box {
            background-color: #080d6e;
            padding: 10px;
        }
        
        #nav {
            background-color: #ffb9b0;
            padding: 10px;
        }
    </style>
    <title>Create Task!</title>
</head>

<body>
    <div id="bigspace">
        <h3>Create New Task</h3>
        <button type="button" class="btn btn-primary btn-sm" style="float: right;"><a style="font-family:Century Gothic;" href="{% url 'todolist:logout' %}">Logout</a></button>
    </div>
    <center>
        <link rel="stylesheet" href="{% static 'css/tutorial.css' %}" media="biasa" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
        <div id="box">
            <h1>Make Your Own To Do List</h1>
        </div>

        <div id="blank"></div>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td>
                        <h5>Task Title</h5>
                    </td>
                    <td><input class="rounded" type="text" name="title" /></td>
                </tr>
                <tr>
                    <td>
                        <h5>Describe Your Task! </h5>
                    </td>
                    <td><input class="rounded" type="text" name="description" /></td>
                </tr>
            </table>
            <center><input class="btn btn-primary btn-sm" type="submit" name="submit" value="Post"></center>
        </form>
    </center>
</body>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}{% load static %}{% block meta %}

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <style>
        h1 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        h3 {
            font-family: "Century Gothic";
            font-weight: bolder;
        }
        
        #bigspace h3 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        #bigspace h4 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        #bigspace h5 {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
        }
        
        #bigspace h3:hover {
            font-family: "Century Gothic";
            font-weight: bolder;
            color: white;
            font-size: 50px;
            transition: 300ms linear;
        }
        
        h5 {
            color: #0d138f;
            font-family: "Century Gothic";
            font-weight: bolder;
        }
        
        b {
            color: #C90668;
            font-family: "Century Gothic";
            font-weight: bolder;
        }
        /* @table (min-width: 700px) {
            background-color: white;
        } */
        
        th {
            color: green;
            font-family: "Century Gothic";
        }
        
        a {
            color: white;
        }
        
        a:hover {
            color: orange;
        }
        
        #nav h5:hover {
            background-color: orange;
            font-size: 26px;
            transition: 300ms linear;
        }
        
        #cont {
            background-color: black;
        }
        
        body {
            background-color: #3BE3D5;
        }
        
        li {
            display: block;
            font-width: bold;
            font-family: "Century Gothic";
        }
        
        li:hover {
            font-size: 20px;
            transition: 300ms linear;
            font-width: bolder;
            font-family: "Century Gothic";
        }
        
        button {
            background-color: #0a68c7;
            border: none;
            border-radius: 8px;
        }
        
        .card button {
            background-color: #3042c9;
            min-width: 100px;
            max-width: 200px;
        }
        
        button:hover {
            font-size: 20px;
            transition: 200ms linear;
        }
        
        .nav-item {
            color: beige;
        }
        
        .card {
            background-color: #f9fce6;
            display: flex;
            min-width: 150px;
        }
        
        .card:hover {
            width: 550px;
            transition: 200ms linear;
        }
        
        @media (max-width:1500px) {
            /* .beeg{

            display:flex;
        } */
            .card {
                display: flex;
            }
        }
        
        @media (min-width:200px) {
            /* .beeg{
            display:flex;
        } */
            .card {
                display: flex;
            }
        }
        
        #blank {
            padding: 10px;
        }
        
        #bigspace {
            background-color: #0d138f;
            padding: 40px;
        }
        
        #box {
            background-color: #080d6e;
            padding: 10px;
        }
        
        #nav {
            background-color: #ffb9b0;
            padding: 10px;
        }
    </style>
    <script>
        //Kak saya dibantu Risa untuk membuat kode ini

        $(document).ready(function() {
            $.get(window.location.href + "json/", function(data) {
                for (i = data.length - 1; i >= 0; i--) {
                    getData(data[i]);
                    deletes(data[i]);
                    update(data[i]);
                }
            });

            // $("#posted").click(function() {
            //     var 
            // });
            $("#posted").click(function() {
                $("#newlist").submit(function(event) {
                    event.preventDefault();
                    $.post(window.location.href + "add/", {
                        title: $("#title").val(),
                        description: $("#description").val(),
                    }).done(function(data) {
                        getData(data);
                        deletes(data);
                        update(data);
                        $("#title").val(""), $("#description").val("");
                        const makeCard = document.getElementById("beeg");
                        makeCard.insertAdjacentHTML("beforeend", $(`#${data.pk}_list`));
                    });
                });
            });

            function getData(data) {
                $("#beeg").append(
                    `
                        <div id="${data.pk}_list" class="card" >
                            <h4>Task Date</h4>
                            <h5>${data.fields.date}</h5>
                            <h4>Task Name</h4>
                            <h5>${data.fields.title}</h5>
                            <h4>Description</h4>
                            <h5>${data.fields.description}</h5>
                            <h4>Are you Done?</h4>
                            <h5 id="${data.pk}-status">${data.fields.finished ? "Done":"Not Yet"}</h5>
                            <h4>Task of User</h4>
                            <h5>{{uname}}</h5>
                            <button class="done"><a id="${data.pk}-finished"> Mark Done </a></button>
                            <button class="delet"><a id="${data.pk}-delete"> Delete </a></button>
                        </div>
                        `
                );
            }

            function update(data) {
                $(`#${data.pk}-finished`).click(function() {
                    $.post(window.location.href + `finish-task/${data.pk}/`, {}).done(
                        (res) => {
                            const status = "Not Yet";

                            $(`#${data.pk}-status`).text(status);
                        }
                    );
                });
                $(`#${data.pk}-finished`).dblclick(function() {
                    $.post(window.location.href + `finish-task/${data.pk}/`, {}).done(
                        (res) => {
                            const status = "Done";
                            $(`#${data.pk}-status`).text(status);
                        }
                    );
                });
            }

            function deletes(data) {
                $(`#${data.pk}-delete`).click(function() {
                    $.post(window.location.href + `delete-task/${data.pk}/`, {}).done(
                        (res) => {
                            $(`#${data.pk}-list`).fadeOut();
                        }
                    );
                });
            }
        });

        // document.getElementById("clicme").onclick = addList
        // refreshtoDolist()
    </script>
</head>

{% endblock meta %} {% block content %}

<body>
    <link rel="stylesheet" href="{% static 'css/tutorial.css' %}" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <div class="modal fade" id="myModals">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Make New Task</h5>
                </div>
                <div class="modal-body">
                    <form method="POST" id="newlist">
                        {% csrf_token %}
                        <table>
                            {{ form.as_table }}
                            <tr>
                                <td>
                                    <h5>Task Title</h5>
                                </td>
                                <td><input class="rounded" type="text" name="title" id="title" /></td>
                            </tr>
                            <tr>
                                <td>
                                    <h5>Describe Your Task! </h5>
                                </td>
                                <td><input class="rounded" type="text" name="description" id="description" /></td>
                            </tr>
                        </table>
                        <center><input class="btn btn-primary btn-sm" type="submit" name="submit" id="posted" value="Post"></center>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
    <center>
        <div id="nav">
            <h5>{{nama}} - {{npm}} - {{uname}}</h5>
            <h5><a style="color:brown" href="{% url 'todolist:logout' %}">Logout</a></h5>
            <button id="clicme" type="button" data-toggle="modal" data-target="#myModals" href="" onclick="$('#myModals').modal('show');">Tambah Task Baru</button>
        </div>
        <div id="bigspace">
            <h1>Task 4-5-6 Assignment PBP/PBD</h1>
            <br>
            <h4>Developer Name: <span style="color:rgb(18, 190, 35)">{{nama}}</span></h4>

            <h4>NPM: <span span style="color:rgb(18, 190, 35)">{{npm}}</span></h4>

            <h4>Current User: <span span style="color:rgb(18, 190, 35)">{{uname}}</span></h4>

            <h5>Sesi terakhir login: {{ last_login }}</h5>
            <br>
            <button><a href="{% url 'todolist:logout' %}">Aku Mau Logout</a></button>

        </div>
    </center>
    <center>
        <br>
        <div id="beeg"></div>
    </center>


</body>
{% endblock content %}